### ISSUE TITLE
flex的盒子设置overflow: ellipsis;

### ISSUE THREAD

**Issue by webooxx** [webooxx/webooxx.github.io#8]
```css

/* 外层盒子，本身也是弹性的，需要 flex:1 撑开 */
.item {
    margin-left: 10px;
    flex: 1;
    display: flex;
    flex-direction: column;
    min-width: 100px; /* <-- 关键*/
}

.item-name {
    font-size: 16px;
    color: #191F25;
    line-height: 20px;
    width: 95%;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}
```
